Removes clear button when the input is disabled
OpenStackweb/openstack-uicore-foundation pull request #106
Opened 2023-02-17 22:17 UTC by tomrndom

<img width="577" alt="image" src="https://user-images.githubusercontent.com/19543853/219803361-88dd5cfe-f790-48ac-928c-f41329caea01.png">

ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3210593

Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>

2023-02-21 18:40 UTC, gcutrini reviewed
LGTM

2023-02-22 14:11 UTC, smarcet requested changes
@tomrndom please review comments

2023-02-22 14:13 UTC, smarcet commented on src/components/inputs/registration-company-input.js
> +const RegistrationCompanyInput = ({ error, value, onChange, id, multi, isMulti, disabled, isDisabled, className, summitId, onError, inputPlaceholder, DDLPlaceholder, ...rest }) => {
and why use 2 flags instead of one ?

2023-02-22 15:30 UTC, smarcet approved these changes
LGTM

2023-02-22 15:30 UTC, merged